config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  resources :prospects,                     only: [:create],           constraints: { format: 'html' }
  resources :offers,        path: :welcome, only: [:show],             constraints: { format: 'html' }

  get 'how-we-are-different',       to: 'static#how_we_are_different',   constraints: { format: 'html' }
  get 'how-it-works',               to: 'static#how_it_works',         constraints: { format: 'html' }
  get 'features',                   to: 'static#features',             constraints: { format: 'html' }
  get 'pricing',                    to: redirect('/features')
  get 'nucleus',                    to: 'static#nucleus',              constraints: { format: 'html' }
  get 'discussions',                to: 'static#discussions',          constraints: { format: 'html' }
  get 'about',                      to: 'static#about',                constraints: { format: 'html' }
  get 'faq',                        to: 'static#faq',                  constraints: { format: 'html' }
  get 'code_of_conduct',            to: 'static#code_of_conduct',      constraints: { format: 'html' }
  get 'commitment_pledge',          to: 'static#commitment_pledge',    constraints: { format: 'html' }
  get 'thanks_guest',               to: 'static#thanks_guest',         constraints: { format: 'html' }
  get 'thanks_join',                to: 'static#thanks_join',          constraints: { format: 'html' }
  get 'thanks_activate',            to: 'static#thanks_activate',      constraints: { format: 'html' }
  get 'sponsorship',                to: 'static#sponsorship',          constraints: { format: 'html' }
  get 'foundation',                 to: 'static#foundation',           constraints: { format: 'html' }
  get 'privacy',                    to: 'static#privacy',              constraints: { format: 'html' }
  get 'terms',                      to: 'static#terms',                constraints: { format: 'html' }
  get 'quick_start',                to: 'static#quick_start',          constraints: { format: 'html' }
  get 'community_canvas',           to: 'static#community_canvas',     constraints: { format: 'html' }

  get 'members',                    to: 'static#members',              constraints: { format: 'html' }

  resources :quarks,                constraints: { format: 'html' }

  resources :pages, path: 'kb',     constraints: { format: 'html' } do
    member do
      get 'featured', to: 'pages#featured'
      put 'like',     to: 'pages#like'
      put 'dislike',  to: 'pages#dislike'
    end
  end
  resources :discussions,   constraints: { format: 'html' } do
    resources :topics,      constraints: { format: 'html' } do
      resources :posts,     constraints: { format: 'html' } do
        collection do
          post :mark_posts_read
        end
        member do
          post :mark_post_read
        end
      end
    end
    collection do
      get                   :search_results
    end
  end

  resources :events,        only: [:index, :create, :show, :update, :destroy], constraints: { format: 'html' } do
    member do
      post :clone,          to: 'events#clone'
    end
  end

  get 'events/calendar',    to: 'calendars#upcoming_events'

  resources :classifieds,   only: [:index, :create, :update, :destroy], constraints: { format: 'html' } do
    member do
      post :ad_response,    to: 'classifieds#ad_response'
    end
  end

  resources :conversations, only: [:index, :create, :destroy],        constraints: { format: 'html' } do
    resources :messages,    only: [:index, :new, :create, :destroy],  constraints: { format: 'html' }
  end

  resources :companies do
    member do
      get     :dashboard
      put     :add_team_member
      put     :update_team_member
      delete  :remove_team_member
      put     :set_sakpi
      delete  :unset_sakpi
    end
  end

  resources :fasts, except: [:index, :show]
  resources :okrs,  except: [:index]
  resources :cards, only:   [:new, :create, :destroy]

  resources :alliances do
    member do
      put     :join_alliance
      put     :add_alliance_member
      delete  :remove_alliance_member
    end
  end

  post  '/accept',              to: 'application#accept_invitation',  constraints: { format: 'html' }

  ActiveAdmin.routes(self)

  post :stripe_webhooks, to: 'cards#stripe_webhooks'

  resources :user_profiles, only:   [:edit, :update]

  devise_scope :user do
    get '/:username' => 'registrations#show', as: :vanity, constraints: { format: 'html'}
    # get '/:username/topics' => 'topics#index', as: :user_topics, constraints: { format: 'html'}
    put  :change_plan,                to: 'registrations#change_plan',    constraints: { format: 'html' }
    put  :declare_trait,              to: 'registrations#declare_trait',  constraints: { format: 'html' }
    put  :declare_skill,              to: 'registrations#declare_skill',  constraints: { format: 'html' }
    delete  :unset_trait,             to: 'registrations#unset_trait',    constraints: { format: 'html' }
    delete  :unset_skill,             to: 'registrations#unset_skill',    constraints: { format: 'html' }
  end

  devise_for :users, controllers: { confirmations: 'confirmations', registrations: 'registrations', sessions: 'sessions' , passwords: 'passwords' }
  as :user do
    get 'users/setup_profile',      to: 'registrations#setup_profile', constraints: { format: 'html' }
    get 'users/set_traits',         to: 'registrations#set_traits',    constraints: { format: 'html' }
    get 'users/set_skills',         to: 'registrations#set_skills',    constraints: { format: 'html' }
    get 'users/membership',         to: 'registrations#membership',    constraints: { format: 'html' }
    put 'users/confirmation',       to: 'confirmations#confirm',       constraints: { format: 'html' }
    put 'users/impersonate',        to: 'sessions#impersonate',        constraints: { format: 'html' }
    put 'users/stop_impersonating', to: 'sessions#stop_impersonating', constraints: { format: 'html' }
  end

end

app/models/discussion.rb
class Discussion < ApplicationRecord
  include Pid

  acts_as_paranoid

  belongs_to  :discussable, polymorphic: true
  belongs_to  :author, class_name: :User
  has_many    :topics, dependent: :destroy
  has_many    :posts, through: :topics

  validates :name,       length: { maximum: 140 }

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :search_results]
  before_action :set_discussion, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def new
    @topic = Topic.new
  end

  # search topic.name and post.body
  # return distinct topics
  def search_results
    if params[:query]
      arr = []
      results    = PgSearch.multisearch(params[:query])
      results.each do |result|
        if result.searchable_type == 'Topic'
          arr << result.searchable_id          if result.searchable.discussion.nucleus?
        elsif result.searchable_type == 'Post'
          arr << result.searchable.topic.id    if result.searchable and result.searchable.topic.discussion.nucleus?
        end
      end
      @topics = Topic.where('topics.id in (?)',arr.uniq).fresh_posts_first
    else
      redirect_to discussions_path, notice: 'Nothing found!'
    end
  end

  def create

    # This action works only for companies and alliances, not for nuc-disco

    if params[:discussion][:company_pid]
      @discussable = Company.find_by_pid(params[:discussion][:company_pid])
      @discussion  = @discussable.discussions.build(discussion_params)
      if @discussion.save
        redirect_to company_path(@discussable), notice: 'Discussion created'
      else
        redirect_to company_path(@discussable), alert: 'There was a problem!'
      end
    end

    if params[:discussion][:alliance_pid]
      @discussable = Alliance.find_by_pid(params[:discussion][:alliance_pid])
      @discussion  = @discussable.discussions.build(discussion_params)
      if @discussion.save
        redirect_to alliance_path(@discussable), notice: 'Discussion created'
      else
        redirect_to alliance_path(@discussable), alert: 'There was a problem!'
      end
    end

  end

  def show
    @topic = Topic.new
  end

  def update
    if @discussion.update(discussion_params)
      if @discussion.discussable.class.name == 'Company'
        redirect_to company_path(@discussion.discussable), notice: 'Discussion updated'
      elsif @discussion.discussable.class.name == 'Alliance'
        redirect_to alliance_path(@discussion.discussable), notice: 'Discussion updated'
      else
        redirect_to discussion_path, notice: 'Discussion updated'
      end
    else
      redirect_to discussion_path(@discussion), alert: 'There was a problem!'
    end
  end

  def destroy
    @discussion.destroy
    redirect_back(fallback_location: root_path)
  end

  private

    def discussion_params
      params.require(:discussion).permit(:name, :slug, :description, :author_id, :discussable_id, :discussable_type, :pid)
    end

    def set_discussion
      @discussion = Discussion.find_by_pid(params[:id])
    end

end

app/views/discussions/_add_modal.html.slim
a data-open='add-discussion'
  i.fa.fa-plus
  | &nbsp;
  ' Add Discussion Subject
.reveal#add-discussion data-reveal=true
  button data-close=true aria-label='Close' type='button' class='close-button'
    span aria-hidden=true
      ' &times;
  p.bold.primary-text.pad-right Add Discussion Subject for #{discussable.name}
  = simple_form_for @discussion, url: discussions_path(@discussion), method: :post do |f|
    = f.hidden_field :author_id,      value: current_user.id  if current_user
    = f.hidden_field :company_pid,    value: discussable.pid  if discussable.class.name == 'Company'
    = f.hidden_field :alliance_pid,   value: discussable.pid  if discussable.class.name == 'Alliance'
    = f.input :name, label: false, autofocus: true, placeholder: 'Not more than 140 characters'
    = f.button :submit, 'Create Discussion Subject', class: 'button expanded accent'

app/views/discussions/_edit_modal.html.slim
a data-open="edit-discussion-#{discussion.pid}"
  i.fa.fa-pencil
  | &nbsp;
  ' Edit
.reveal id="edit-discussion-#{discussion.pid}" data-reveal=true
  button data-close=true aria-label='Close' type='button' class='close-button'
    span aria-hidden=true
      ' &times;
  .row
    .medium-12.columns
      p.bold.primary-text.little-snug-bottom Update Discussion Subject
  .row
    .medium-2.columns
      p.little-snug-bottom.text-right In:
    .medium-10.columns
      p.bold= discussable.name
  .row
    .medium-12.columns
      = simple_form_for discussion, url: discussion_path(discussion), method: :put do |f|
        /= f.hidden_field :author_id,      value: current_user.id  if current_user and params[:action] == 'new'
        = f.hidden_field :company_pid,    value: discussable.pid  if discussable.class.name == 'Company'
        = f.hidden_field :alliance_pid,   value: discussable.pid  if discussable.class.name == 'Alliance'
        = f.input :name, label: false, autofocus: true, placeholder: 'Not more than 140 characters'
        = f.button :submit, 'Edit Discussion Subject', class: 'button expanded accent'

app/views/discussions/_form.html.slim
= simple_form_for(@discussion) do |f|
  = f.error_notification

  .form-inputs
    = f.hidden_field :author_id,    value: current_user.id       if current_user          and @discussion.new_record?
    = f.hidden_field :company_pid,  value: params[:company_pid]  if params[:company_pid]  and @discussion.new_record?
    = f.hidden_field :alliance_pid, value: params[:alliance_pid] if params[:alliance_pid] and @discussion.new_record?
    = f.input :name, placeholder: 'Type a short name for this Discussion'

  .form-actions
    .row
      .medium-12.columns
        .button-group
          = f.button :submit, class: 'button'
          = link_to 'Exit', :back, class: 'button accent'

app/views/discussions/edit.html.slim
- content_for :page_header do
  h2.bold.little-space-top.little-space-bottom.white-text.text-center
    ' Update Discussion
.row
  .medium-8.medium-offset-2.columns
    p.text-right.snug-top.space-bottom
      ' Discussions are where you get answers and share ideas

    = render 'form'

app/views/discussions/new.html.slim
- content_for :page_header do
  h2.bold.little-space-top.little-space-bottom.white-text.text-center
    ' Create Discussion
.row
  .medium-8.medium-offset-2.columns
    p.text-right.snug-top.space-bottom
      ' Discussions are where you get answers and share ideas

    = render 'form'

app/views/discussions/search_results.html.slim
- content_for :page_header do
  h4.bold.little-space-top.medium-grey-text.text-center
    ' Search results:
  h2.bold.white-text.text-center.title-font
    ' “#{params[:query]}” #{number_with_delimiter(@topics.count)} matching
    ' #{'result'.pluralize(@topics.count)}

.row
  .large-12.columns
    .float-left
      p.snug-top.space-bottom
        = link_to discussions_path do
          i.fa.fa-arrow-left
          | &nbsp;
          | &nbsp;
          ' Return to Discussions
.row
  .large-5.columns.large-push-7
    h5.bold.space-top &nbsp;
    = render 'partials/search_form_disco'
  .large-7.columns.large-pull-5
    h5.bold.space-top Topic threads containing this search result:
    - if @topics.present?
      - @topics.each do |topic|
        .callout.accent.shadow.space-bottom
          - if current_user and (topic.author_id == current_user.id or current_user.admin?)
            .float-right
              ul.dropdown.menu data-dropdown-menu=true
                li
                  = link_to '#' do
                    i.fa.fa-ellipsis-v.fainter
                  ul.menu data-dropdown-menu=true data-alignment='left'
                    li
                      = render 'topics/edit_modal', topic: topic
                    li= link_to discussion_topic_path(topic.discussion,topic), data: { confirm: 'Really destroy this Topic and all it’s Posts?' }, method: :delete do
                      i.fa.fa-trash-o
                      | &nbsp;
                      ' Delete
          - if current_user and current_user.confirmed? and topic.posts.present? and topic.posts.unread_by(current_user).present?
            .float-left
              h5= link_to mark_posts_read_discussion_topic_posts_path(topic.discussion,topic), data: { confirm: 'Really mark all these Posts as read?' }, method: :post do
                i.fa.fa-comments.fa-lg.red-text
                | &nbsp;
                | &nbsp;
          h4.bold
            - if current_user and current_user.confirmed?
              = link_to topic.name, discussion_topic_path(@discussion,topic)
            - else
              = topic.name
          p.faint.little-snug-top
            ' (Started by #{link_to topic.author.name, vanity_path(topic.author.username)}.
            = topic_meta(topic)
            ' )







          /- if current_user and topic.posts.present? and topic.posts.unread_by(current_user).present?
            .float-left
              h4.space-top
                i.fa.fa-comments.red-text
                | &nbsp;
          /h4.bold.space-top
            = link_to topic.name, discussion_topic_path(topic.discussion,topic)
          /p.faint.little-snug-top
            ' (Part of #{link_to topic.discussion.name, discussion_path(topic.discussion)}. Created #{time_ago_in_words(topic.created_at)} ago, contains #{topic_meta(topic)})
    - else
      .callout
        p.text-center Nothing here!

app/views/discussions/show.html.slim
- content_for :page_title do
  ' Startup Alliance – Discussion Subject: #{@discussion.name}

- content_for :page_header do
  h4.bold.little-space-top.medium-grey-text.text-center
    ' Subject:
  h2.bold.white-text.text-center.title-font
    = @discussion.name
.row
  .large-12.columns
    ul.breadcrumbs.snug-top.space-bottom
      - if @discussion.discussable_type == 'Alliance'
        li.bold= link_to @discussion.discussable.name, alliance_path(@discussion.discussable, anchor: 'discussions')
      - if @discussion.discussable_type == 'Company'
        li.bold= link_to @discussion.discussable.name, company_path(@discussion.discussable, anchor: 'discussions')
      - if !@discussion.discussable
        li.bold= link_to 'Nucleus Discussions', discussions_path
      li.bold= @discussion.name
- if current_user and !current_user.confirmed?
  .row
    .medium-11.medium-offset-1.columns
      .callout.small.alert.little-space-top.snug-bottom
        p.text-center
          span.has-tip data-tooltip=true aria-haspopup=true data-click-open='false' title=ACCOUNT_ACTIVATION_TIP
            = link_to 'Activate your account', new_confirmation_path(current_user)
          '  to access the discussions!
.row
  .medium-4.columns.medium-push-8
    p &nbsp;
    .callout.small
      p.bold Subject list:
      ul.little-snug-top
        - if !@discussion.discussable
          - discos = Discussion.where(nucleus: true).all.order(:name)
        - else
          - discos = @discussion.discussable.discussions.order(:name)
        - discos.each do |discussion|
          - if discussion != @discussion
            li.little-space-bottom
              - if current_user and discussion.posts.present? and discussion.posts.unread_by(current_user).present?
                .float-left
                  = link_to mark_posts_read_discussion_topic_posts_path(discussion,discussion.topics.last), data: { confirm: 'Really mark all contained Posts as read?' }, method: :post do
                    i.fa.fa-comments.red-text
                  | &nbsp;
              = link_to discussion.name, discussion_path(discussion)
              br
              .faint= discussion_meta(discussion)
          - else
            li.little-space-bottom.bold
              = discussion.name
              span.normal
                .faint= discussion_meta(discussion)

  .medium-7.medium-offset-1.columns.medium-pull-4
    - if current_user and current_user.confirmed?
      p= render 'topics/add_modal'
    - else
      p &nbsp;
    - if @discussion.topics.present?
      - @discussion.topics.fresh_posts_first.each do |topic|
        .callout.accent.shadow.space-bottom
          - if @discussion.discussable
            - if current_user and (@discussion.discussable.creator_id == current_user.id or topic.author_id == current_user.id or current_user.admin?)
              .float-right
                ul.dropdown.menu data-dropdown-menu=true
                  li
                    = link_to '#' do
                      i.fa.fa-ellipsis-v.fainter
                    ul.menu data-dropdown-menu=true  data-alignment='left'
                      li
                        = render 'topics/edit_modal', topic: topic
                      li= link_to discussion_topic_path(topic.discussion,topic), data: { confirm: 'Really destroy this Topic and all it’s Posts?' }, method: :delete do
                        i.fa.fa-trash-o
                        | &nbsp;
                        ' Delete
          - else
            - if current_user and (topic.author_id == current_user.id or current_user.admin?)
              .float-right
                ul.dropdown.menu data-dropdown-menu=true
                  li
                    = link_to '#' do
                      i.fa.fa-ellipsis-v.fainter
                    ul.menu data-dropdown-menu=true  data-alignment='left'
                      li
                        = render 'topics/edit_modal', topic: topic
                      li= link_to discussion_topic_path(topic.discussion,topic), data: { confirm: 'Really destroy this Topic and all it’s Posts?' }, method: :delete do
                        i.fa.fa-trash-o
                        | &nbsp;
                        ' Delete
          - if current_user and current_user.confirmed? and topic.posts.present? and topic.posts.unread_by(current_user).present?
            .float-left
              h5= link_to mark_posts_read_discussion_topic_posts_path(topic.discussion,topic), data: { confirm: 'Really mark all these Posts as read?' }, method: :post do
                i.fa.fa-comments.red-text
                | &nbsp;
                | &nbsp;
          h4.bold
            - if current_user and current_user.confirmed?
              = link_to topic.name, discussion_topic_path(@discussion,topic)
            - else
              = topic.name
          p.faint.little-snug-top
            ' (Started by #{link_to topic.author.name, vanity_path(topic.author.username)}.
            = topic_meta(topic)
            ' )
    - else
      .callout.accent
        p.text-center No Topic Threads yet!
        - if current_user and current_user.confirmed?
          p.text-center.snug-bottom= render 'topics/add_modal'
        - elsif current_user and !current_user.confirmed?
          p.text-center.snug-bottom
            span.has-tip data-tooltip=true aria-haspopup=true data-click-open='false' title=ACCOUNT_ACTIVATION_TIP
              = link_to 'Activate your account', new_confirmation_path(current_user)
            '  to access the discussions!



  /.medium-8.medium-offset-2.columns
    - if @discussion.topics.present?
      h4 &nbsp;
      - @discussion.topics.fresh_posts_first.each do |topic|
        - if @discussion.discussable
          - if current_user and (@discussion.discussable.creator_id == current_user.id or topic.author_id == current_user.id or current_user.admin?)
            .float-right
              ul.dropdown.menu data-dropdown-menu=true
                li
                  = link_to '#' do
                    i.fa.fa-ellipsis-v.fainter
                  ul.menu data-dropdown-menu=true  data-alignment='left'
                    li
                      = render 'topics/edit_modal', topic: topic
                    li= link_to discussion_topic_path(topic.discussion,topic), data: { confirm: 'Really destroy this Topic and all it’s Posts?' }, method: :delete do
                      i.fa.fa-trash-o
                      | &nbsp;
                      ' Delete
        - else
          - if current_user and (topic.author_id == current_user.id or current_user.admin?)
            .float-right
              ul.dropdown.menu data-dropdown-menu=true
                li
                  = link_to '#' do
                    i.fa.fa-ellipsis-v.fainter
                  ul.menu data-dropdown-menu=true  data-alignment='left'
                    li
                      = render 'topics/edit_modal', topic: topic
                    li= link_to discussion_topic_path(topic.discussion,topic), data: { confirm: 'Really destroy this Topic and all it’s Posts?' }, method: :delete do
                      i.fa.fa-trash-o
                      | &nbsp;
                      ' Delete
        - if current_user and topic.posts.present? and topic.posts.unread_by(current_user).present?
          .float-left
            h5= link_to mark_posts_read_discussion_topic_posts_path(topic.discussion,topic), data: { confirm: 'Really mark all these Posts as read?' }, method: :post do
              i.fa.fa-comments.fa-lg.red-text
              | &nbsp;
              | &nbsp;
        h4.bold
          = link_to topic.name, discussion_topic_path(@discussion,topic)
        p.faint.little-snug-top
          ' (Started by #{link_to topic.author.name, vanity_path(topic.author.username)}.
          = topic_meta(topic)
          ' )
    - else
      .callout
        p.text-center No Topic threads yet!
        p.text-center.snug-bottom= render 'topics/add_modal'