config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  resources :prospects,                     only: [:create],           constraints: { format: 'html' }
  resources :offers,        path: :welcome, only: [:show],             constraints: { format: 'html' }

  get 'how-we-are-different',       to: 'static#how_we_are_different',   constraints: { format: 'html' }
  get 'how-it-works',               to: 'static#how_it_works',         constraints: { format: 'html' }
  get 'features',                   to: 'static#features',             constraints: { format: 'html' }
  get 'pricing',                    to: redirect('/features')
  get 'nucleus',                    to: 'static#nucleus',              constraints: { format: 'html' }
  get 'discussions',                to: 'static#discussions',          constraints: { format: 'html' }
  get 'about',                      to: 'static#about',                constraints: { format: 'html' }
  get 'faq',                        to: 'static#faq',                  constraints: { format: 'html' }
  get 'code_of_conduct',            to: 'static#code_of_conduct',      constraints: { format: 'html' }
  get 'commitment_pledge',          to: 'static#commitment_pledge',    constraints: { format: 'html' }
  get 'thanks_guest',               to: 'static#thanks_guest',         constraints: { format: 'html' }
  get 'thanks_join',                to: 'static#thanks_join',          constraints: { format: 'html' }
  get 'thanks_activate',            to: 'static#thanks_activate',      constraints: { format: 'html' }
  get 'sponsorship',                to: 'static#sponsorship',          constraints: { format: 'html' }
  get 'foundation',                 to: 'static#foundation',           constraints: { format: 'html' }
  get 'privacy',                    to: 'static#privacy',              constraints: { format: 'html' }
  get 'terms',                      to: 'static#terms',                constraints: { format: 'html' }
  get 'quick_start',                to: 'static#quick_start',          constraints: { format: 'html' }
  get 'community_canvas',           to: 'static#community_canvas',     constraints: { format: 'html' }

  get 'members',                    to: 'static#members',              constraints: { format: 'html' }

  resources :quarks,                constraints: { format: 'html' }

  resources :pages, path: 'kb',     constraints: { format: 'html' } do
    member do
      get 'featured', to: 'pages#featured'
      put 'like',     to: 'pages#like'
      put 'dislike',  to: 'pages#dislike'
    end
  end
  resources :discussions,   constraints: { format: 'html' } do
    resources :topics,      constraints: { format: 'html' } do
      resources :posts,     constraints: { format: 'html' } do
        collection do
          post :mark_posts_read
        end
        member do
          post :mark_post_read
        end
      end
    end
    collection do
      get                   :search_results
    end
  end

  resources :events,        only: [:index, :create, :show, :update, :destroy], constraints: { format: 'html' } do
    member do
      post :clone,          to: 'events#clone'
    end
  end

  get 'events/calendar',    to: 'calendars#upcoming_events'

  resources :classifieds,   only: [:index, :create, :update, :destroy], constraints: { format: 'html' } do
    member do
      post :ad_response,    to: 'classifieds#ad_response'
    end
  end

  resources :conversations, only: [:index, :create, :destroy],        constraints: { format: 'html' } do
    resources :messages,    only: [:index, :new, :create, :destroy],  constraints: { format: 'html' }
  end

  resources :companies do
    member do
      get     :dashboard
      put     :add_team_member
      put     :update_team_member
      delete  :remove_team_member
      put     :set_sakpi
      delete  :unset_sakpi
    end
  end

  resources :fasts, except: [:index, :show]
  resources :okrs,  except: [:index]
  resources :cards, only:   [:new, :create, :destroy]

  resources :alliances do
    member do
      put     :join_alliance
      put     :add_alliance_member
      delete  :remove_alliance_member
    end
  end

  post  '/accept',              to: 'application#accept_invitation',  constraints: { format: 'html' }

  ActiveAdmin.routes(self)

  post :stripe_webhooks, to: 'cards#stripe_webhooks'

  resources :user_profiles, only:   [:edit, :update]

  devise_scope :user do
    get '/:username' => 'registrations#show', as: :vanity, constraints: { format: 'html'}
    # get '/:username/topics' => 'topics#index', as: :user_topics, constraints: { format: 'html'}
    put  :change_plan,                to: 'registrations#change_plan',    constraints: { format: 'html' }
    put  :declare_trait,              to: 'registrations#declare_trait',  constraints: { format: 'html' }
    put  :declare_skill,              to: 'registrations#declare_skill',  constraints: { format: 'html' }
    delete  :unset_trait,             to: 'registrations#unset_trait',    constraints: { format: 'html' }
    delete  :unset_skill,             to: 'registrations#unset_skill',    constraints: { format: 'html' }
  end

  devise_for :users, controllers: { confirmations: 'confirmations', registrations: 'registrations', sessions: 'sessions' , passwords: 'passwords' }
  as :user do
    get 'users/setup_profile',      to: 'registrations#setup_profile', constraints: { format: 'html' }
    get 'users/set_traits',         to: 'registrations#set_traits',    constraints: { format: 'html' }
    get 'users/set_skills',         to: 'registrations#set_skills',    constraints: { format: 'html' }
    get 'users/membership',         to: 'registrations#membership',    constraints: { format: 'html' }
    put 'users/confirmation',       to: 'confirmations#confirm',       constraints: { format: 'html' }
    put 'users/impersonate',        to: 'sessions#impersonate',        constraints: { format: 'html' }
    put 'users/stop_impersonating', to: 'sessions#stop_impersonating', constraints: { format: 'html' }
  end

end

app/models/topic.rb
class Topic < ApplicationRecord
  include Pid
  include PgSearch
  multisearchable against: [:name]

  acts_as_paranoid

  belongs_to  :discussion
  belongs_to  :author,  class_name: :User, counter_cache: true
  has_many    :posts,   dependent: :destroy

  validates :name,          length: { maximum: 140 }

  scope :fresh_posts_first, -> { includes(:posts).order('posts.updated_at desc') }

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :update, :destroy]

  # POST
  def create
    # if %w[entrepreneur alliance company].any? { |necessary_subscriptions| current_user.subscription == necessary_subscriptions }
    @topic = Topic.new(topic_params)
    discussion = Discussion.find params[:topic][:discussion_id]
    if @topic.save
      redirect_to discussion_topic_path(@topic.discussion,@topic), notice: 'Topic was successfully created.'
    else
      redirect_to discussion_path(@topic.discussion), alert: 'There was a problem!'
    end
    # else
    #   redirect_to pricing_path(goal: 'topic'), alert: 'Please upgrade your Membership Plan!'
    # end
  end

  def show
    @post = Post.new
    # mark_mine_read(@topic.posts)
  end

  def update
    # if %w[entrepreneur alliance company].any? { |necessary_subscriptions| current_user.subscription == necessary_subscriptions }
    if @topic.update(topic_params)
      redirect_to discussion_path(@topic.discussion), notice: 'Topic was successfully updated.'
    else
      redirect_to discussion_path(@topic.discussion), alert: 'There was a problem!'
    end
    # else
    #   redirect_to pricing_path(goal: 'topic'), alert: 'Please upgrade your Membership Plan!'
    # end
  end

  def destroy
    # if %w[entrepreneur alliance company].any? { |necessary_subscriptions| current_user.subscription == necessary_subscriptions }
    discussion = Discussion.find(@topic.discussion_id)
    @topic.destroy
    redirect_to discussion_path(discussion)
    # else
    #   redirect_to pricing_path(goal: 'topic'), alert: 'Please upgrade your Membership Plan!'
    # end
  end

  private

    # mark these posts as read by current_user
    def mark_mine_read(these)
      Post.mark_collection_as_read(these, current_user)
    end

    def set_topic
      @topic = Topic.find_by_pid(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:name, :discussion_id, :author_id)
    end

end

app/views/topics/_add_modal.html.slim
a data-open='add-topic'
  i.fa.fa-plus
  | &nbsp;
  ' Start
  - if @discussion.topics.blank?
    ' the first
  - else
    ' new
  ' Topic Thread
  /' to this Discussion subject
.reveal#add-topic data-reveal=true
  button data-close=true aria-label='Close' type='button' class='close-button'
    span aria-hidden=true
      ' &times;
  .row
    .medium-12.columns
      p.bold.primary-text.little-snug-bottom Add Topic Thread
    .row
      .medium-2.columns
        p.little-snug-bottom.text-right Within:
      .medium-10.columns
        p.bold= @discussion.name
    .row
      .medium-12.columns
        = simple_form_for @topic, url: discussion_topics_path(@discussion), method: :post do |f|
          = f.hidden_field :author_id,     value: current_user.id  if current_user
          = f.hidden_field :discussion_id, value: @discussion.id
          = f.input :name, label: false, autofocus: true, placeholder: 'Not more than 140 characters'
          = f.button :submit, 'Create Topic', class: 'button expanded accent'

app/views/topics/_add_topic_modal.html.slim
a data-open='add-topic'
  i.fa.fa-plus
  | &nbsp;
  ' Add Topic
.reveal#add-topic data-reveal=true
  button data-close=true aria-label='Close' type='button' class='close-button'
    span aria-hidden=true
      ' &times;
  p.bold.primary-text.pad-right Add Topic within #{@discussion.name}
  = simple_form_for @topic, url: discussion_topics_path(@discussion), method: :post do |f|
    = f.hidden_field :author_id,     value: current_user.id  if current_user
    = f.hidden_field :discussion_id, value: @discussion.id
    = f.input :name, label: false, autofocus: true, placeholder: 'Not more than 140 characters'
    = f.button :submit, 'Create Topic', class: 'button expanded accent'

app/views/topics/_edit_topic_modal.html.slim
a data-open="edit-topic-#{topic.pid}"
  i.fa.fa-pencil
.reveal id="edit-topic-#{topic.pid}" data-reveal=true
  button data-close=true aria-label='Close' type='button' class='close-button'
    span aria-hidden=true
      ' &times;
  p.bold.primary-text.pad-right Update Topic within #{@discussion.name}
  = simple_form_for topic, url: discussion_topic_path(@discussion,topic), method: :put do |f|
    = f.hidden_field :author_id,         value: current_user.id  if current_user
    = f.hidden_field :discussion_id,     value: @discussion.id
    = f.input :name, label: false, autofocus: true, placeholder: 'Not more than 140 characters'
    = f.button :submit, 'Update Topic', class: 'button expanded accent'

app/views/topics/show.html.slim
- content_for :page_title do
  ' Startup Alliance – Topic: #{@topic.name}

- content_for :page_header do
  h4.bold.little-space-top.medium-grey-text.text-center
    ' Topic:
  h2.bold.white-text.text-center.title-font
    = @topic.name

.row
  .large-12.columns
    ul.breadcrumbs.snug-top.space-bottom
      - if @topic.discussion.discussable_type == 'Alliance'
        li.bold= link_to @topic.discussion.discussable.name, alliance_path(@topic.discussion.discussable, anchor: 'discussions')
      - if @topic.discussion.discussable_type == 'Company'
        li.bold= link_to @topic.discussion.discussable.name, company_path(@topic.discussion.discussable, anchor: 'discussions')
      - if !@topic.discussion.discussable
        li.bold= link_to 'Nucleus Discussions', discussions_path
      li.bold= link_to @topic.discussion.name, discussion_path(@topic.discussion)
      li.bold= @topic.name

.row
  .medium-10.medium-offset-1.columns
    - if current_user and current_user.confirmed?
      p= render 'post/add_modal'
    - elsif current_user and !current_user.confirmed?
      p
        span.has-tip data-tooltip=true aria-haspopup=true data-click-open='false' title=ACCOUNT_ACTIVATION_TIP
          ' Activate your account
        '  to Post or Reply!

    - if @topic.posts.present?
      = nested_posts @topic.posts.arrange(order: :created_at)
      - if current_user and @topic.posts.unread_by(current_user).present?
        .callout.dark-grey
          p= link_to mark_posts_read_discussion_topic_posts_path(@topic.discussion,@topic), data: { confirm: 'Really mark all these Posts as read?' }, method: :post do
            i.fa.fa-comments.fa-lg.red-text
            | &nbsp;
            | &nbsp;
            span.bold
              ' Mark all unread Posts in this Thread as read
    - else
      .callout.dark-grey
        p.text-center No Posts yet!
        - if current_user and current_user.confirmed?
          p.text-center.snug-bottom= render 'post/add_modal'
        - elsif current_user and !current_user.confirmed?
          p.text-center.snug-bottom
            span.has-tip data-tooltip=true aria-haspopup=true data-click-open='false' title=ACCOUNT_ACTIVATION_TIP
              ' Activate your account
            '  to Post in this Topic thread!