config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  resources :prospects,                     only: [:create],           constraints: { format: 'html' }
  resources :offers,        path: :welcome, only: [:show],             constraints: { format: 'html' }

  get 'how-we-are-different',       to: 'static#how_we_are_different',   constraints: { format: 'html' }
  get 'how-it-works',               to: 'static#how_it_works',         constraints: { format: 'html' }
  get 'features',                   to: 'static#features',             constraints: { format: 'html' }
  get 'pricing',                    to: redirect('/features')
  get 'nucleus',                    to: 'static#nucleus',              constraints: { format: 'html' }
  get 'discussions',                to: 'static#discussions',          constraints: { format: 'html' }
  get 'about',                      to: 'static#about',                constraints: { format: 'html' }
  get 'faq',                        to: 'static#faq',                  constraints: { format: 'html' }
  get 'code_of_conduct',            to: 'static#code_of_conduct',      constraints: { format: 'html' }
  get 'commitment_pledge',          to: 'static#commitment_pledge',    constraints: { format: 'html' }
  get 'thanks_guest',               to: 'static#thanks_guest',         constraints: { format: 'html' }
  get 'thanks_join',                to: 'static#thanks_join',          constraints: { format: 'html' }
  get 'thanks_activate',            to: 'static#thanks_activate',      constraints: { format: 'html' }
  get 'sponsorship',                to: 'static#sponsorship',          constraints: { format: 'html' }
  get 'foundation',                 to: 'static#foundation',           constraints: { format: 'html' }
  get 'privacy',                    to: 'static#privacy',              constraints: { format: 'html' }
  get 'terms',                      to: 'static#terms',                constraints: { format: 'html' }
  get 'quick_start',                to: 'static#quick_start',          constraints: { format: 'html' }
  get 'community_canvas',           to: 'static#community_canvas',     constraints: { format: 'html' }

  get 'members',                    to: 'static#members',              constraints: { format: 'html' }

  resources :quarks,                constraints: { format: 'html' }

  resources :pages, path: 'kb',     constraints: { format: 'html' } do
    member do
      get 'featured', to: 'pages#featured'
      put 'like',     to: 'pages#like'
      put 'dislike',  to: 'pages#dislike'
    end
  end
  resources :discussions,   constraints: { format: 'html' } do
    resources :topics,      constraints: { format: 'html' } do
      resources :posts,     constraints: { format: 'html' } do
        collection do
          post :mark_posts_read
        end
        member do
          post :mark_post_read
        end
      end
    end
    collection do
      get                   :search_results
    end
  end

  resources :events,        only: [:index, :create, :show, :update, :destroy], constraints: { format: 'html' } do
    member do
      post :clone,          to: 'events#clone'
    end
  end

  get 'events/calendar',    to: 'calendars#upcoming_events'

  resources :classifieds,   only: [:index, :create, :update, :destroy], constraints: { format: 'html' } do
    member do
      post :ad_response,    to: 'classifieds#ad_response'
    end
  end

  resources :conversations, only: [:index, :create, :destroy],        constraints: { format: 'html' } do
    resources :messages,    only: [:index, :new, :create, :destroy],  constraints: { format: 'html' }
  end

  resources :companies do
    member do
      get     :dashboard
      put     :add_team_member
      put     :update_team_member
      delete  :remove_team_member
      put     :set_sakpi
      delete  :unset_sakpi
    end
  end

  resources :fasts, except: [:index, :show]
  resources :okrs,  except: [:index]
  resources :cards, only:   [:new, :create, :destroy]

  resources :alliances do
    member do
      put     :join_alliance
      put     :add_alliance_member
      delete  :remove_alliance_member
    end
  end

  post  '/accept',              to: 'application#accept_invitation',  constraints: { format: 'html' }

  ActiveAdmin.routes(self)

  post :stripe_webhooks, to: 'cards#stripe_webhooks'

  resources :user_profiles, only:   [:edit, :update]

  devise_scope :user do
    get '/:username' => 'registrations#show', as: :vanity, constraints: { format: 'html'}
    # get '/:username/topics' => 'topics#index', as: :user_topics, constraints: { format: 'html'}
    put  :change_plan,                to: 'registrations#change_plan',    constraints: { format: 'html' }
    put  :declare_trait,              to: 'registrations#declare_trait',  constraints: { format: 'html' }
    put  :declare_skill,              to: 'registrations#declare_skill',  constraints: { format: 'html' }
    delete  :unset_trait,             to: 'registrations#unset_trait',    constraints: { format: 'html' }
    delete  :unset_skill,             to: 'registrations#unset_skill',    constraints: { format: 'html' }
  end

  devise_for :users, controllers: { confirmations: 'confirmations', registrations: 'registrations', sessions: 'sessions' , passwords: 'passwords' }
  as :user do
    get 'users/setup_profile',      to: 'registrations#setup_profile', constraints: { format: 'html' }
    get 'users/set_traits',         to: 'registrations#set_traits',    constraints: { format: 'html' }
    get 'users/set_skills',         to: 'registrations#set_skills',    constraints: { format: 'html' }
    get 'users/membership',         to: 'registrations#membership',    constraints: { format: 'html' }
    put 'users/confirmation',       to: 'confirmations#confirm',       constraints: { format: 'html' }
    put 'users/impersonate',        to: 'sessions#impersonate',        constraints: { format: 'html' }
    put 'users/stop_impersonating', to: 'sessions#stop_impersonating', constraints: { format: 'html' }
  end

end

app/models/company.rb
class Company < ApplicationRecord
  include Pid
  include CountryName
  include Webmeet
  has_many    :discussions, as: :discussable, dependent: :destroy
  has_many    :company_users, dependent: :destroy
  has_many    :team, through: :company_users, source: :user
  belongs_to  :creator, class_name: :User
  has_many    :okrs, dependent: :destroy
  has_many    :fasts, dependent: :destroy
  has_many    :company_sakpis, dependent: :destroy
  has_many    :sakpis, through: :company_sakpis

  accepts_nested_attributes_for :company_users

  validates :url, url: { allow_nil: true, allow_blank: true, no_local: true }

  enum state: {
      Active:           0,
      Frozen:           1,
      Closed:           2
  }

  enum phases: {
      Ideation:         0,
      Validation:       1,
      Operational:      2,
      Growth:           3,
      Diversification:  4
  }

  # used to test company_user.role (enum)
  def team_member(user)
    CompanyUser.where(user_id: user.id, company_id: self.id).first
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  include DateConverter
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_company, only: [:dashboard, :show, :add_team_member, :update_team_member, :remove_team_member, :set_sakpi, :unset_sakpi, :edit, :update, :destroy]
  load_and_authorize_resource

  def dashboard
    # render layout: 'application_blank'
  end


  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.where(is_unlisted: false).all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @discussion = Discussion.new
  end

  # GET /companies/new
  def new
    if %w[company].any? { |necessary_subscriptions| current_user.subscription == necessary_subscriptions }
      @company = Company.new
    else
      redirect_to pricing_path(goal: 'company'), alert: 'Please upgrade to a Company Membership!'
    end
  end

  # GET /companies/1/edit
  def edit
    if %w[company].any? { |necessary_subscriptions| current_user.subscription == necessary_subscriptions }
      true
    else
      redirect_to pricing_path(goal: 'company'), alert: 'Please upgrade to a Company Membership!'
    end
  end

  def set_sakpi
    if @company and params[:sakpi_id] and params[:level]
      sakpi = CompanySakpi.where(
          company_id:  @company.id,
          sakpi_id: params[:sakpi_id]
      ).first_or_create
      sakpi.update(level: params[:level])
      set_sakpi_index
    end
    redirect_back(fallback_location: company_path, notice: 'You set your SAKPI')
  end

  def unset_sakpi
    if @company and params[:sakpi_id]
      CompanySakpi.where(company_id: @company.id, sakpi_id: params[:sakpi_id]).first.destroy
      set_sakpi_index
    end
    redirect_back(fallback_location: company_path, alert: 'You unset your SAKPI')
  end

  # PUT /companies/1/add_team_member
  def add_team_member
    team_member = User.where('lower(username) = ?', params[:username].downcase).first
    if team_member.blank?
      redirect_back(fallback_location: company_path, alert: 'Nobody with that username!')
    elsif @company.team.include? team_member
      redirect_back(fallback_location: company_path, alert: 'Already a team member!')
    else
      if params[:role].present?
        role = params[:role]
      else
        role = 'Employee'
      end
      CompanyUser.create(
          user_id: team_member.id,
          company_id: @company.id,
          role: role,
          equity: params[:equity]
      )
      redirect_back(fallback_location: company_path, notice: 'Team member added.')
    end
  end

  # PUT /companies/1/update_team_member
  def update_team_member
    user = User.find_by_pid(params[:user_pid])
    if user
      company_user = CompanyUser.where(company_id: @company.id).where(user_id: user.id)
      if company_user
        company_user.update(role: params[:company_user][:role])
      end
      redirect_back(fallback_location: company_path, notice: 'Team role updated.')
    end
  end

  # DELETE
  def remove_team_member
    @team_member = User.find_by_pid(params[:team_member_pid])
    reassign_okr_ownership
    if @company.team.count > 1
      @company.team.delete(@team_member)
      redirect_back(fallback_location: company_path, notice: 'Team member removed.')
    else
      redirect_back(fallback_location: company_path, alert: 'Cannot remove the last team member, please contact support.')
    end
  end

  # POST /companies
  # POST /companies.json
  def create
    if %w[company].any? { |necessary_subscriptions| current_user.subscription == necessary_subscriptions }
      @company = Company.where(company_params).first_or_initialize
      if @company.new_record?
        @company.founded = string_to_date(params[:company][:founded])
        respond_to do |format|
          if @company.save
            Notifier.jk_object_created(@company).deliver
            @company.update(invite_token: SecureRandom.urlsafe_base64)
            @company.team << current_user
            format.html { redirect_to @company, notice: 'Company was successfully created.' }
            format.json { render :show, status: :created, location: @company }
          else
            format.html { render :new }
            format.json { render json: @company.errors, status: :unprocessable_entity }
          end
        end
      else
        redirect_to company_path(@company), notice: 'Company already exists!'
      end
    else
      redirect_to pricing_path(goal: 'company'), alert: 'Please upgrade to a Company Membership!'
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    if %w[company].any? { |necessary_subscriptions| current_user.subscription == necessary_subscriptions }
      founded = string_to_date(params[:company][:founded])
      params[:company].delete :founded
      if current_user == @company.creator
        if @company.update(company_params)
          @company.update_attribute(:founded, founded)
          respond_to do |format|
            format.html { redirect_to @company, notice: 'Company was successfully updated.' }
            format.json { render :show, status: :ok, location: @company }
          end
        else
          respond_to do |format|
            format.html { render :edit }
            format.json { render json: @company.errors, status: :unprocessable_entity }
          end
        end
      else
        redirect_back(fallback_location: root_path, alert: 'You are not the creator of this Company!')
      end
    else
      redirect_to pricing_path(goal: 'company'), alert: 'Please upgrade to a Company Membership!'
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    # TODO what about the team, CompanySakpis and OKRs?
    @company.destroy
    respond_to do |format|
      format.html { redirect_to vanity_path(current_user.username), notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def reassign_okr_ownership
      okrs = Okr.where(owner_id: @team_member.id).all
      if okrs.present?
        Okr.where(owner_id: @team_member.id).each do |okr|
          okr.update(owner_id: okr.company.creator.id)
        end
      end
    end

    # Update company.sakpi_index with new total
    def set_sakpi_index
      cs = @company.company_sakpis
      @company.update(sakpi_index: cs.sum(:level))
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find_by_pid(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:is_unlisted, :name, :mission, :primary_market, :webmeet_code, :sakpi_index, :phases, :url, :country_code, :time_zone, :founded, :recruiting, :creator_id, :state)
    end
end

app/helpers/company_helper.rb
module CompanyHelper

  def company_pvo_url
    WEBRTC_PRIVATE_URL + @company.webmeet_code
  end

  def team_role(company,user)
    company_user = CompanyUser.where(company_id: company.id).where(user_id: user.id).first
    if company_user
      company_user.role
    else
      'unknown'
    end
  end

  def team_roles
    roles = [
      ['Owner','Owner'],
      ['Employee','Employee'],
      ['Advisor','Advisor'],
      ['Consultant','Consultant'],
      ['Investor','Investor']
    ]
  end

end

app/views/companies/_company_card.html.slim
.card
  .card-divider.primary-background
    .row
      .large-12.columns
        - if current_user and @company.team.include?(current_user) and @company.team_member(current_user).role == 'Owner'
          .float-right
            = link_to edit_company_path(@company) do
              i.fa.fa-pencil.white-text
        h1.bold.white-text.wide-line-height.text-center
          = @company.name
    - if @company.recruiting
      .row
        .large-12.columns
          p.bold.alert-text.text-right.snug-top.snug-bottom We’re recruiting!

  .card-section
    .row
      .medium-10.medium-offset-1.columns

        - if params[:invite] and params[:invite] == @company.invite_token
          .callout
            p.bold You are invited to join our team
            - if current_user
              = render 'partials/accept_invitation_form'
            - else
              = render 'partials/join_form', acqsrc: 'company_invite'

        - if @company.mission.present?
           p.bold.little-space-top Mission statement:
           p.snug-top= @company.mission

        - if @company.primary_market.present?
          p.bold Primary market:
          p.snug-top= @company.primary_market

        = render 'summary'

app/views/companies/_discussions.html.slim
.row
  - if current_user and @company.team.include?(current_user)
    .large-5.columns.large-push-7
      .float-right.space-top
        a data-open='disco-info'
          i.fa.fa-lg.fa-info-circle
        = render 'partials/quick_ref_disco'
      h5.bold.space-top &nbsp
      .callout.small.alert
        p
          span.bold
            ' Note:
          ' Posts here are visible only to
          em
            | the team members of this Company Workspace
          ' . Nobody else can read your post.
      - if @company.discussions.present?
        - if discussable_topics(@company).present?
          .callout.small
            p.bold Recently active Topics:
            ul.little-snug-top
              - discussable_topics(@company).fresh_posts_first.limit(8).each do |topic|
                li.little-space-bottom
                  - if current_user and topic.posts.present? and topic.posts.unread_by(current_user).present?
                    .float-right
                      = link_to mark_posts_read_discussion_topic_posts_path(topic.discussion,topic), data: { confirm: 'Really mark all these Posts as read?' }, method: :post do
                        i.fa.fa-comments.fa-lg.red-text
                      | &nbsp;
                      | &nbsp;
                  .bold= link_to topic.name, discussion_topic_path(topic.discussion,topic)
                  .scale-to-90 In: #{link_to topic.discussion.name, discussion_path(topic.discussion)}
                  /.scale-to-90 = topic_meta(topic)
        - else
          .callout.small
            p.text-center Nothing yet!
      - else
        .callout.small
          p.text-center Nothing yet!
    .large-7.columns.large-pull-5
      - if current_user and (@company.creator == current_user or current_user.team_role(@company) == 'Owner' or current_user.admin?)
        p.space-top.snug-bottom= render 'discussions/add_modal', discussable: @company
      - else
        p.space-top.snug-bottom &nbsp;
      - if @company.discussions.present?
        - @company.discussions.order(:name).each do |discussion|
          .callout.primary.shadow.space-bottom
            - if current_user and (current_user.team_role(@company) == 'Owner' or current_user.admin?)
              .float-right.little-space-top
                ul.dropdown.menu data-dropdown-menu=true
                  li
                    = link_to '#' do
                      i.fa.fa-ellipsis-v.fainter
                    ul.menu data-dropdown-menu=true data-alignment='left'
                      li= render 'discussions/edit_modal', discussable: @company, discussion: discussion
                      li= link_to discussion, data: { confirm: "Really destroy “#{discussion.name}” and all contained Topics and Posts?" }, method: :delete do
                        i.fa.fa-trash-o
                        | &nbsp;
                        ' Delete
            - if current_user and discussion.posts.present? and discussion.posts.unread_by(current_user).present?
              .float-left
                = link_to mark_posts_read_discussion_topic_posts_path(discussion,discussion.topics.last), data: { confirm: 'Really mark all contained Posts as read?' }, method: :post do
                  i.fa.fa-comments.fa-lg.red-text
            h4.bold.text-center
              ' #{link_to discussion.name, discussion_path(discussion)}
            p.little-snug-top.faint.text-center
              = discussion_meta(discussion)
      - else
        .callout.little-space-top
          p.text-center No Discussions yet!
  - else
    .medium-12.columns
      .callout
        p.text-center.space-top Team discussions only visible to the Company Team.

app/views/companies/_form.html.slim
= simple_form_for(@company) do |f|
  = f.error_notification

  .form-inputs
    .row
      = f.hidden_field :creator_id, value: current_user.id if params[:action] == 'new'
      .medium-4.columns
        = f.input :name, label: 'Company name', placeholder: 'Company name', required: true
      .medium-4.columns
        = f.input :url, label: 'URL', placeholder: 'Company website'
      .medium-4.columns
        = f.input :phases, label: 'Company stage', collection: Company.phases.keys
    = f.input :is_unlisted, label: 'Activate stealth mode to hide this Company Workspace'
    = f.input :recruiting, label: 'Display recruiting notification'
    = f.input :mission, label: 'Mission statement (Help people understand the value your company provides)', as: :text, input_html: { rows: '3' }, placeholder: 'Company mission statement and value proposition.'
    = f.input :primary_market, label: 'Primary market served (Help people understand who you help and where those people are)', as: :text, input_html: { rows: '2' }, placeholder: 'Briefly describe the market to which you provide value'
    .row
      .medium-4.columns
        = f.input :founded, label: 'Date founded', as: :string, placeholder: 'mm/dd/yyyy', input_html: { value: f.object.founded.try(:strftime,'%m/%d/%Y') }
      .medium-4.columns
        = f.input :country_code, label: 'Country', include_blank: 'Select your country', input_html: { class: 'chosen-select' }
      .medium-4.columns
        = f.input :time_zone, label: 'Time zone', priority: ActiveSupport::TimeZone.us_zones, include_blank: 'Select your time zone', input_html: { class: 'chosen-select' }
    /- if params[:action] == 'new'
      .callout.small.accent
        .row
          .medium-6.columns
            p.space-top.text-center Please specify your ownership equity:
          .medium-6.columns
            = f.simple_fields_for :company_user do |cu|
              = cu.input :equity, collection: CompanyUser.equities.keys, label: 'My equity percentage', default: false

  .form-actions
    .row
      .medium-12.columns
        .button-group
          = f.button :submit, class: 'button'
          = link_to 'Exit', :back, class: 'button accent'

app/views/companies/_masthead.html.slim
- content_for :page_header do
  - if current_user and @company.team.include?(current_user) and current_user.team_role(@company) == 'Owner'
    .float-right
      .pad-right= link_to edit_company_path(@company) do
        i.fa.fa-pencil.white-text
  - if @company.is_unlisted
    .float-left
      p.bold.medium-grey-text.text-right.space-bottom
        i.fa.fa-user-secret
        | &nbsp;
        ' Stealth mode
  - if !@company.recruiting
    h2.bold.little-space-top.little-space-bottom.white-text.text-center
      = @company.name
  - else
    h2.bold.little-space-top.white-text.text-center
      = @company.name
    h4.bold.medium-grey-text.text-center We’re recruiting!

app/views/companies/_overview.html.slim
/.row data-equalizer=true
.row
  .medium-6.columns
    .callout.shadow.little-space-top data-equalizer-watch=true
      h5.bold Mission statement:
      - if @company.mission.present?
        h5.text-center= @company.mission
      - else
        p.text-center not set
  .medium-6.columns
    .callout.shadow.little-space-top data-equalizer-watch=true
      h5.bold Primary market:
      - if @company.primary_market.present?
        h5.text-center= @company.primary_market
      - else
        p.text-center not set
.row
  .large-6.large-offset-3.medium-8.medium-offset-2.columns
    = render 'summary'

app/views/companies/_sakpis.html.slim
.row
  .medium-10.medium-offset-1.columns
    h5.bold.primary-text.little-space-bottom
      .float-right
        p.faint
          - if current_user and current_user.team_role(@company) == 'Owner'
            a data-open='set-sakpis'
              i.fa.fa-pencil
          = render 'partials/set_sakpis_modal'

      span.has-tip data-tooltip=true aria-haspopup=true data-click-open='false' title=SAKPI_TIP
        ' Key Performance Indicators:
    - if current_user and current_user.confirmed? and @company.team_member(current_user)
      - sakpis = Sakpi.all.order(:name)
      .callout.shadow
        - sakpis.each do |sakpi|
          .progress.accent role='progressbar' tabindex='0' aria-valuenow='0' aria-valuemin='0' aria-valuemax='100'
            - cs = CompanySakpi.where(company_id: @company.id, sakpi_id: sakpi.id).first
            - if cs.present?
              .progress-meter style="width: #{cs.level*10}%"
                p.bold.meter-text= sakpi.name.html_safe
            - else
              .progress-meter style="width: 0%"
                p.bold.meter-text= sakpi.name.html_safe
    - else
      p.text-center.space-top
        em
          ' OKRs are only visible to the Company Team.

app/views/companies/_summary.html.slim
- if @company.phases.present?
  .float-right
    p
      a data-open='stage-info'
        = @company.phases
        | &nbsp;
        i.fa.fa-info-circle
      = render 'partials/quick_ref_stages'
  p Company stage:

- if @company.url.present?
  .float-right
    p.little-snug-top
      = link_to @company.url, target: '_blank' do
        ' #{@company.url}
  p.little-snug-top Website:

- if @company.okrs
  .float-right
    p.little-snug-top= number_with_delimiter(@company.okrs.count)
  p.little-snug-top Lifetime OKRs:

- if @company.sakpi_index
  .float-right
    p.little-snug-top= @company.sakpi_index
  p.little-snug-top SAKPI index:

- if @company.founded.present?
  .float-right
    p.little-snug-top= @company.founded.strftime('%B %e, %Y')
  p.little-snug-top Founded:

- if @company.time_zone.present?
  .float-right
    p.little-snug-top= ActiveSupport::TimeZone.new(@company.time_zone)
  p.little-snug-top Time zone:

- if @company.country_code.present?
  .float-right
    p.little-snug-top= ISO3166::Country(@company.country_code).try(:name)
  p.little-snug-top Country:

/.float-right
/  p.little-snug-top= link_to @company.creator.name, vanity_path(@company.creator.username)
/p.little-snug-top Listed by:

/.float-right
/  p.little-snug-top= @company.created_at.strftime('%B %e, %Y')
/p.little-snug-top Listed on:

/.float-right
/  p.little-snug-top.snug-bottom= @company.updated_at.strftime('%B %e, %Y')
/p.little-snug-top.snug-bottom Last update:

app/views/companies/_tabs.html.slim
ul.tabs.accent-background.shadow#tool-tabs data-tabs=true data-deep-link="true" data-update-history="true"
  - if !current_user or (current_user and !@company.team.include?(current_user))
    li.tabs-title.is-active
      a.bold href='#overview' aria-selected='true'
        ' Overview
  - else
    li.tabs-title
      a.bold href='#overview'
        ' Overview
  li.tabs-title
    a.bold href='#team'
      ' Team
  li.tabs-title
    a.bold href='#sakpis'
      ' SAKPIs
  - if current_user and @company.team.include? current_user
    li.tabs-title.is-active
      a.bold href='#fasts' aria-selected='true'
        ' FAST
  - else
    li.tabs-title
      a.bold href='#fasts'
        ' FAST
  li.tabs-title
    a.bold href='#okrs'
      ' OKRs
  li.tabs-title
    a.bold href='#discussions'
      ' Discussions
      - if current_user and @company.discussions.any? { |disco| disco.posts.unread_by(current_user).present? if disco.posts.where.not(author_id: current_user.id).present? }
        | &nbsp;
        span.white-text
          i.fa.fa-comments
  li.tabs-title
    a.bold href='#office'
      ' Virtual Office

.tabs-content.shadow data-tabs-content='tool-tabs'
  - if !current_user
    .tabs-panel.is-active#overview
      = render 'overview'
  - else
    .tabs-panel#overview
      = render 'overview'
  .tabs-panel#team
    = render 'team'
  .tabs-panel#sakpis
    = render 'sakpis'
  - if current_user and @company.team.include? current_user
    .tabs-panel.is-active#fasts
      = render 'fasts'
  - else
    .tabs-panel#fasts
      = render 'fasts'
  .tabs-panel#okrs
    = render 'okrs'
  .tabs-panel#discussions
    = render 'discussions'
  .tabs-panel#office
    = render 'virtual_office'

app/views/companies/_team.html.slim
.row.small-up-2.medium-up-3
  - @company.team.order(created_at: :desc).each_with_index do |member,i|
    .column
      .callout.small.shadow
        - if current_user and @company.team.include?(member) and unread_posts_count(@company.discussions,member) != 0
          p.scale-to-90.text-center.alert-text.little-snug-bottom
            ' #{unread_posts_count(@company.discussions,member)} unread #{'post'.pluralize(unread_posts_count(@company.discussions,member))}!
        - if current_user != member
          .float-right
            ul.menu.simple.little-space-top
              - if current_user and current_user.confirmed? and current_user != member
                li
                  = link_to conversations_path(sender_pid: current_user.pid, recipient_pid: member.pid), method: :post do
                    i.fa.fa-comments-o
              - if current_user == @company.creator and member != current_user
                li
                  = link_to remove_team_member_company_path(team_member_pid: member.pid), data: {:confirm => 'Really remove this team member?'}, method: :delete do
                    i.fa.fa-trash-o

        p
          ' #{image_tag gravatar_url("#{member.email}", 48)}
          | &nbsp;
          ' #{link_to member.name, vanity_path(member.username), class: 'bold'}

        .float-right
          p.little-snug-top.faint
            = team_role(@company, member)
            - if current_user and current_user == @company.creator
              a.faint data-open="edit-team-role-#{i}"
                | &nbsp;
                | &nbsp;
                i.fa.fa-pencil
              .reveal id="edit-team-role-#{i}" data-reveal=true
                button data-close=true aria-label='Close' type='button' class='close-button'
                  span aria-hidden=true
                    ' &times;
                p.bold.primary-text Update team role for #{member.name}
                = simple_form_for member.company_users.first, url: update_team_member_company_path(user_pid: member.pid) , method: :put do |f|
                  = f.input :role, label: false, include_blank: false, collection: team_roles, input_html: { value: f.object.role }
                  .row
                    .medium-12.columns
                      .button-group
                        = submit_tag 'Update team role', class: 'button expanded accent'

        p.little-snug-top.faint Role:

        .float-right
          p.little-snug-top.faint= render 'partials/user_si_ti_display', user: member
        p.little-snug-top.faint Skill index / Trait index:

        .float-right
          p.little-snug-top.faint= member.okrs.count
        p.little-snug-top.faint OKR ownership:

        - if member.time_zone.present?
          .float-right
            p.little-snug-top.faint= ActiveSupport::TimeZone.new(member.time_zone)
          p.little-snug-top.faint Time zone:

        - if member.country_code.present?
          .float-right
            p.little-snug-top.faint= ISO3166::Country(member.country_code).name
          p.little-snug-top.faint Country:




  - if current_user and @company.team.include?(current_user) and current_user.team_role(@company) == 'Owner'
    .column
      .callout.shadow
        .bold.text-center.snug-bottom= render 'add_to_team'

app/views/companies/_video_conferencing.html.slim
- if current_user and @company.team.include?(current_user)
  .small-12.columns
    .callout data-closable=true
      button data-close=true aria-label='Close' type='button' class='close-button'
        span aria-hidden=true
          ' &times;
      p.faint.pad-right
        ' Unite the team and aid collaboration with any time, any place video conferences. (Any team member can use this any time.)
.row
  .medium-10.medium-offset-1.columns
    h5.bold.primary-text
      span.has-tip data-tooltip=true aria-haspopup=true data-click-open='false' title=WEBRTC_TIP
        ' Live Video Conferencing:
    - if current_user and @company.webmeet_url.present? and @company.team.include?(current_user)
      p.text-center.snug-bottom= link_to 'Access the Video Conference', @company.webmeet_url, target: '_blank', class: 'button shadow-4dp'
    - else
      p.space-top.text-center
        em Video conferencing only available to the company team.