config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  resources :prospects,                     only: [:create],           constraints: { format: 'html' }
  resources :offers,        path: :welcome, only: [:show],             constraints: { format: 'html' }

  get 'how-we-are-different',       to: 'static#how_we_are_different',   constraints: { format: 'html' }
  get 'how-it-works',               to: 'static#how_it_works',         constraints: { format: 'html' }
  get 'features',                   to: 'static#features',             constraints: { format: 'html' }
  get 'pricing',                    to: redirect('/features')
  get 'nucleus',                    to: 'static#nucleus',              constraints: { format: 'html' }
  get 'discussions',                to: 'static#discussions',          constraints: { format: 'html' }
  get 'about',                      to: 'static#about',                constraints: { format: 'html' }
  get 'faq',                        to: 'static#faq',                  constraints: { format: 'html' }
  get 'code_of_conduct',            to: 'static#code_of_conduct',      constraints: { format: 'html' }
  get 'commitment_pledge',          to: 'static#commitment_pledge',    constraints: { format: 'html' }
  get 'thanks_guest',               to: 'static#thanks_guest',         constraints: { format: 'html' }
  get 'thanks_join',                to: 'static#thanks_join',          constraints: { format: 'html' }
  get 'thanks_activate',            to: 'static#thanks_activate',      constraints: { format: 'html' }
  get 'sponsorship',                to: 'static#sponsorship',          constraints: { format: 'html' }
  get 'foundation',                 to: 'static#foundation',           constraints: { format: 'html' }
  get 'privacy',                    to: 'static#privacy',              constraints: { format: 'html' }
  get 'terms',                      to: 'static#terms',                constraints: { format: 'html' }
  get 'quick_start',                to: 'static#quick_start',          constraints: { format: 'html' }
  get 'community_canvas',           to: 'static#community_canvas',     constraints: { format: 'html' }

  get 'members',                    to: 'static#members',              constraints: { format: 'html' }

  resources :quarks,                constraints: { format: 'html' }

  resources :pages, path: 'kb',     constraints: { format: 'html' } do
    member do
      get 'featured', to: 'pages#featured'
      put 'like',     to: 'pages#like'
      put 'dislike',  to: 'pages#dislike'
    end
  end
  resources :discussions,   constraints: { format: 'html' } do
    resources :topics,      constraints: { format: 'html' } do
      resources :posts,     constraints: { format: 'html' } do
        collection do
          post :mark_posts_read
        end
        member do
          post :mark_post_read
        end
      end
    end
    collection do
      get                   :search_results
    end
  end

  resources :events,        only: [:index, :create, :show, :update, :destroy], constraints: { format: 'html' } do
    member do
      post :clone,          to: 'events#clone'
    end
  end

  get 'events/calendar',    to: 'calendars#upcoming_events'

  resources :classifieds,   only: [:index, :create, :update, :destroy], constraints: { format: 'html' } do
    member do
      post :ad_response,    to: 'classifieds#ad_response'
    end
  end

  resources :conversations, only: [:index, :create, :destroy],        constraints: { format: 'html' } do
    resources :messages,    only: [:index, :new, :create, :destroy],  constraints: { format: 'html' }
  end

  resources :companies do
    member do
      get     :dashboard
      put     :add_team_member
      put     :update_team_member
      delete  :remove_team_member
      put     :set_sakpi
      delete  :unset_sakpi
    end
  end

  resources :fasts, except: [:index, :show]
  resources :okrs,  except: [:index]
  resources :cards, only:   [:new, :create, :destroy]

  resources :alliances do
    member do
      put     :join_alliance
      put     :add_alliance_member
      delete  :remove_alliance_member
    end
  end

  post  '/accept',              to: 'application#accept_invitation',  constraints: { format: 'html' }

  ActiveAdmin.routes(self)

  post :stripe_webhooks, to: 'cards#stripe_webhooks'

  resources :user_profiles, only:   [:edit, :update]

  devise_scope :user do
    get '/:username' => 'registrations#show', as: :vanity, constraints: { format: 'html'}
    # get '/:username/topics' => 'topics#index', as: :user_topics, constraints: { format: 'html'}
    put  :change_plan,                to: 'registrations#change_plan',    constraints: { format: 'html' }
    put  :declare_trait,              to: 'registrations#declare_trait',  constraints: { format: 'html' }
    put  :declare_skill,              to: 'registrations#declare_skill',  constraints: { format: 'html' }
    delete  :unset_trait,             to: 'registrations#unset_trait',    constraints: { format: 'html' }
    delete  :unset_skill,             to: 'registrations#unset_skill',    constraints: { format: 'html' }
  end

  devise_for :users, controllers: { confirmations: 'confirmations', registrations: 'registrations', sessions: 'sessions' , passwords: 'passwords' }
  as :user do
    get 'users/setup_profile',      to: 'registrations#setup_profile', constraints: { format: 'html' }
    get 'users/set_traits',         to: 'registrations#set_traits',    constraints: { format: 'html' }
    get 'users/set_skills',         to: 'registrations#set_skills',    constraints: { format: 'html' }
    get 'users/membership',         to: 'registrations#membership',    constraints: { format: 'html' }
    put 'users/confirmation',       to: 'confirmations#confirm',       constraints: { format: 'html' }
    put 'users/impersonate',        to: 'sessions#impersonate',        constraints: { format: 'html' }
    put 'users/stop_impersonating', to: 'sessions#stop_impersonating', constraints: { format: 'html' }
  end

end

app/models/offer.rb
class Offer < ApplicationRecord
  include Pid
  belongs_to  :plan
  has_many    :prospects
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  before_action :prepare_offer, only: [:show]

  # GET /welcome/:pid
  def show
    render layout: 'application_blank'
  end

  private

    def prepare_offer
      @offer = Offer.find_by_pid(offer_params[:id])
      @coupon = Stripe::Coupon.retrieve(@offer.coupon) if @offer and @offer.coupon.present?
      unless @offer
        redirect_to root_path, notice: 'Invalid or expired code' and return
      end
    end

    def offer_params
      params.permit(:id)
    end

end

app/views/offers/_join_form.html.slim
.callout.success.shadow-6dp
  h5.bold
    ' #{@offer.plan.display_name} —
    - if @offer.coupon.present?
      ' #{@coupon.percent_off}% off
      - if @coupon.duration_in_months.present? and @coupon.duration != 'once'
        ' for #{@coupon.duration_in_months} months
      - elsif @coupon.duration == 'once'
        - invoice_amount = (@offer.plan.amount * @coupon.percent_off)/10000
        ' first year
        ' (Only #{number_to_currency(invoice_amount)})
    - else
      ' #{@offer.plan.display_price} a #{@offer.plan.duration.humanize}
  - if !@offer.plan.trial_period_days.nil? and @coupon.percent_off != 100
    p.little-snug-top #{@offer.plan.trial_period_days} day risk free trial (No card required)
  p.faint.little-snug-top Regular price: #{@offer.plan.display_price} a #{@offer.plan.duration.humanize}
  - if @offer.valid_through.present?
    p This offer expires #{@offer.valid_through.strftime('%B %e, %Y')}.
  = simple_form_for(:user, url: registration_path(:user)) do |f|
    = f.error_notification

    = f.hidden_field :plan_id,  value: @offer.plan.id
    = f.hidden_field :coupon,   value: @offer.coupon
    = f.hidden_field :acqsrc,   value: 'offer_pid_'+@offer.pid

    /p.faint.snug-bottom
      em Membership is open to committed entrepreneurs, advisors and investors
    .row.collapse
      .small-6.columns
        = f.input :email, placeholder: 'Enter your email...', label: false
      .small-6.columns
        = f.button :submit, @offer.cta_button_text, class: 'postfix expanded bold success'
    .row
      .medium-12.columns
        .snug-top= label_tag :terms do
          = check_box_tag :terms, true
          ' I accept the #{link_to 'privacy statement', privacy_path, target: '_blank'} and #{link_to 'terms of use', terms_path, target: '_blank'}.
        .g-recaptcha data-sitekey=RECAPTCHA_SITE style="transform:scale(0.9); transform-origin:0 0"

app/views/offers/_video_embed.html.slim
.responsive-embed.widescreen.shadow-6dp
  iframe src="https://www.youtube-nocookie.com/embed/#{@offer.video_url}?rel=0" frameborder='2' allowfullscreen='true' class='youtube-player' type='text/html'

app/views/offers/_video_offer.html.slim
.responsive-embed.widescreen.shadow-6dp
  iframe src="https://www.youtube-nocookie.com/embed/#{@offer.video_url}?rel=0" frameborder='2' allowfullscreen='true' class='youtube-player' type='text/html'

app/views/offers/show.html.slim
- content_for :page_title do
  ' Startup Alliance welcomes you

- content_for :page_header do
  h2.bold.little-space-top.white-text.text-center = @offer.header_1
  h4.bold.medium-grey-text.text-center            = @offer.header_2
  /- if @offer.valid_through.present?
    h5.bold.medium-grey-text.text-center  Offer expires #{@offer.valid_through.strftime('%B %e, %Y')}


.row
  .medium-12.columns
    = link_to root_path do
      .space-top.text-center= image_tag 'sa_banner_2.svg', width: '260px'
      h5.primary.bold.little-less-space-top.text-center Accelerating the globalization of entrepreneurship.

- if @offer.box_1.present?
  .row
    .large-8.large-offset-2.medium-10.medium-offset-1.columns
      p.snug-top.show-for-medium &nbsp;
      .callout.primary.shadow-6dp
        .primary.text-center= markdown @offer.box_1

- if @offer.video_url.present?
  .row
    .large-8.large-offset-2.medium-10.medium-offset-1.columns
      p.snug-top.show-for-medium &nbsp;
      .little-space-top= render 'offers/video_embed'

p.snug-top.show-for-medium &nbsp;
.callout.success
  .row
    .medium-12.columns
      h3.bold.text-center.little-space-bottom= @offer.offer_lead_in
  .row
    .large-6.large-offset-3.medium-8.medium-offset-2.columns
      .callout.success-background.coupon-border
        h4.bold.text-center= @offer.plan.display_name
        - if !@offer.plan.trial_period_days.nil? and @coupon.percent_off != 100
          p.text-center.little-snug-top #{@offer.plan.trial_period_days} day risk free trial (No card required)
        p.text-center.little-snug-top Regular price: #{@offer.plan.display_price} a #{@offer.plan.duration.humanize}

        - if @coupon
          h4.bold.text-center
            ' #{@coupon.percent_off}% off
            - if @coupon.duration_in_months.present? and @coupon.duration != 'once'
              ' for #{@coupon.duration_in_months} months
            - elsif @coupon.duration == 'once'
              - invoice_amount = (@offer.plan.amount * @coupon.percent_off)/10000
              ' first year
              ' (Only #{number_to_currency(invoice_amount)})
          - if @offer.valid_through.present?
            p.text-center.little-snug-top  Offer expires #{@offer.valid_through.strftime('%B %e, %Y')}
        - else
          h4.bold.text-center Only #{@offer.plan.display_price} a #{@offer.plan.duration.humanize}
      = markdown @offer.benefit_lead_in


.callout.primary.snug-top

  - if @offer.box_2.present?
    .row
      .large-8.large-offset-2.medium-10.medium-offset-1.columns
        p.snug-top.show-for-medium &nbsp;
        .callout.shadow-6dp
          .primary= markdown @offer.box_2

  - if @offer.box_3.present?
    .row
      .large-8.large-offset-2.medium-10.medium-offset-1.columns
        p.snug-top.show-for-medium &nbsp;
        .callout.shadow-6dp
          .primary= markdown @offer.box_3
          /- else
            h2.bold.little-space-top.primary This is how it works:
          /- if @offer.plan
            h4.bold.little-space-top With #{@offer.plan.display_name} you can:
          /- else
            h4.bold.little-space-top Subscribe and you will get:

          /- if @offer.plan and @offer.plan.short_name != 'associate'
            h5.bold.little-space-top.text-center #{@offer.plan.trial_period_days} day free trial, no card required!
          /- elsif @offer.plan and @offer.plan.short_name == 'associate'
            p.bold.little-space-top.text-center Associate Membership is free

          /- if @offer.plan and @offer.plan.short_name != 'associate'
  .row
    .large-8.large-offset-2.medium-12.columns
      p.snug-top.show-for-medium &nbsp;
      = render 'offers/join_form'

  .row
    .large-10.large-offset-1.medium-12.columns
      p.snug-top.show-for-medium &nbsp;
      = render 'partials/storybox'

.callout.primary-background.snug-top
  .row
    .medium-12.columns
      h2.bold.white-text.text-center.space-top Better. Together.
      ul.menu.align-right.snug-top.snug-bottom
        li= mail_to 'hello@startupalliance.com', 'Email us', encode: 'hex', class: 'medium-grey-text'
        li= link_to 'How it Works', how_it_works_path, target: '_blank', class: 'medium-grey-text'
        li= link_to 'How We’re Different', how_we_are_different_path, target: '_blank', class: 'medium-grey-text'